#!/bin/bash

#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1,mem=1g,walltime=1:00:00
#PBS -N freight_train

source /home/meccanica/helbouhali/.bashrc

module use /software/spack/spack/share/spack/modules/linux-rocky8-sandybridge/
module load openfoam

cd /home/meccanica/helbouhali/HPC/freight_train_CFD/simulation
time ./Allrun_cluster > /home/meccanica/helbouhali/HPC/freight_train_CFD/simulation/output.txt