#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Alternative decomposeParDict name:
decompDict="-decomposeParDict system/decomposeParDict"
## Standard decomposeParDict name:
# unset decompDict
mkdir -p constant/triSurface

cp -f \
    ~/OpenFOAM/bux-v2306/run/Geometrie/treno15gradi/train2.stl \
    constant/triSurface/
cp -f \
    ~/OpenFOAM/bux-v2306/run/Geometrie/treno15gradi/pareti_galleria.stl \
    constant/triSurface/    

cp -f \
    ~/OpenFOAM/bux-v2306/run/Geometrie/treno15gradi/pareti_avanti.stl \
    constant/triSurface/
cp -f \
    ~/OpenFOAM/bux-v2306/run/Geometrie/treno15gradi/pareti_dietro.stl \
    constant/triSurface/

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication $decompDict decomposePar

# Using distributedTriSurfaceMesh?
if foamDictionary -entry geometry -value system/snappyHexMeshDict | \
   grep -q distributedTriSurfaceMesh
then
    echo "surfaceRedistributePar does not need to be run anymore"
    echo " - distributedTriSurfaceMesh will do on-the-fly redistribution"
fi

runParallel $decompDict snappyHexMesh -overwrite

#runParallel $decompDict topoSet

#runParallel $decompDict createPatch -overwrite

#- For non-parallel running: - set the initial fields
# restore0Dir

#- For parallel running: set the initial fields
restore0Dir -processor

runParallel $decompDict patchSummary

runParallel $decompDict potentialFoam -writephi

runParallel $decompDict checkMesh -writeFields '(nonOrthoAngle)' -constant

runParallel $decompDict $(getApplication)

runApplication reconstructParMesh -constant

runApplication reconstructPar   #-latestTime

touch trenone.foam

#------------------------------------------------------------------------------
