#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
# Alternative decomposeParDict name:
#decompDict="-decomposeParDict system/decomposeParDict.6"
## Standard decomposeParDict name:
# unset decompDict

# Define the local directory where the simulation is run
localDir='/home/meccanica/helbouhali/HPC'

# copy train surface from resources directory
mkdir -p "$localDir"/freight_train_CFD/simulation/constant/triSurface

cp -f \
    "$localDir"/Geometrie/treno0gradi/train2.stl \
    constant/triSurface/


mkdir -p "$localDir"/freight_train_CFD/simulation/results

# Run the applications and return the log files to the results directory


runApplication surfaceFeatureExtract

runApplication blockMesh

runParallel $decompDict patchSummary

runParallel $decompDict potentialFoam -writephi

runParallel $decompDict checkMesh -writeFields '(nonOrthoAngle)' -constant

runParallel $decompDict $(getApplication)

runApplication reconstructParMesh -constant

runApplication reconstructPar   #-latestTime

touch trenone.foam
#------------------------------------------------------------------------------
