#!/bin/sh
#module use /software/spack/spack/share/spack/modules/linux-rocky8-sandybridge/
#module load openfoam
echo $WM_PROJECT_DIR
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
## Standard decomposeParDict name:
# unset decompDict

# Define the local directory where the simulation is run
localDir='/home/meccanica/helbouhali/HPC'

# Alternative decomposeParDict name:
decompDict="-decomposeParDict /home/meccanica/helbouhali/HPC/freight_train_CFD/simulation/system/decomposeParDict"

# copy train surface from resources directory
mkdir -p "$localDir"/freight_train_CFD/simulation/constant/triSurface

cp -f \
    "$localDir"/Geometrie/treno0gradi/train2.stl \
    constant/triSurface/


mkdir -p "$localDir"/freight_train_CFD/simulation/results

# Run the applications and return the log files to the results directory

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication $decompDict decomposePar


if foamDictionary -entry geometry -value system/snappyHexMeshDict | \
   grep -q distributedTriSurfaceMesh
then
    echo "surfaceRedistributePar does not need to be run anymore"
    echo " - distributedTriSurfaceMesh will do on-the-fly redistribution"
fi

runParallel $decompDict snappyHexMesh -overwrite

restore0Dir -processor

runParallel $decompDict patchSummary

runParallel $decompDict potentialFoam -writephi

runParallel $decompDict checkMesh -writeFields '(nonOrthoAngle)' -constant

runParallel $decompDict $(getApplication)

runApplication reconstructParMesh -constant

runApplication reconstructPar   #-latestTime

touch trenone.foam
#------------------------------------------------------------------------------
